---
title: "Emma data analysis"
author: "AG"
date: "14 September 2017"
output: pdf_document
---

```{r setup, include=FALSE}
library(knitr)
knitr::opts_chunk$set(echo = FALSE, message=FALSE, warning=FALSE)
library(plyr)
library(reshape2)
library(ggplot2)
library(gridExtra)
library(pander)
library(dplyr)
library(lubridate)
library(tidyr)
library(data.table)
rm(list=ls() ) 
```

```{r importdatasets}
data.path <-"original-data"
EA1 <- read.csv(file.path(data.path,"Equine_assessment_form_1-170914163241042.csv"))
EA2 <- read.csv(file.path(data.path,"Equine_assessment_form_2-170914163239558.csv"))
OR1 <- read.csv(file.path(data.path,"Owner_donkey_records_1-170914163240433.csv"))
DC1 <- read.csv(file.path(data.path,"Donkey_clinic_records_1-170914163244183.csv"))
LE1 <- read.csv(file.path(data.path,"Donkey_lesion_form-170914163240011.csv"))
#turn into a tible
#EA1 <- tbl_df(EA1)
EA2 <- tbl_df(EA2)
#Turn into a df
#EA1 <- as.data.frame(EA1)
```


```{r data cleaning vacc15}
#remove duplicates (there turn out not to be any duiplicates here)
dup <- distinct(EA1, AnswerCode, .keep_all = TRUE)
dup1 <- distinct(EA2, AnswerCode, .keep_all = TRUE)
EA1 <- EA1[!duplicated(EA1$AnswerCode), ]
EA2 <- EA2[!duplicated(EA2$AnswerCode), ]
OR1 <- OR1[!duplicated(OR1$AnswerCode), ]
DC1 <- DC1[!duplicated(DC1$AnswerCode), ]
LE1 <- LE1[!duplicated(LE1$AnswerCode), ]


```


The cascade of forms is like this

* OWNER RECORDS = DC1 (03/10/17 to 28/04/17) + OR1 (23/05/17 to 25/07/17)
+ the link for Owner is $ownerID$ in DC/OR and EA1/EA2

* EQUINE RECORDS = EA1 (03/10/17 to 28/04/17) + (23/05/17 to 25/07/17)
+ the link to the horse is $AnswerCode$ in EA1/EA2 and ParentID in LE1

* LESION RECORDS = LE1 (03/10/17 to 25/07/17)

```{r joining EA1 and EA2}

##EA1 and EA2 share a number of common columns - need to join the rows based on common columns

```

```{r joining DC1 and OR2}

##DC1 and OR1 share a number of common columns - need to join the rows based on common columns

```

```{r linking Parent form to Daughter form}

# The cascade of forms is like this
# OWNER RECORDS = DC1 (03/10/17 to 28/04/17) + OR1 (23/05/17 to 25/07/17)
# EQUINE RECORDS = EA1 (03/10/17 to 28/04/17) + (23/05/17 to 25/07/17)
# LESION RECORDS = LE1 (03/10/17 to 25/07/17)

#DC1

# EA1 and EA2 are parent forms - they contain 

```




```{r import maps}
### get data from shapefile
library(maptools)
IND_3 <- readShapePoly(file.path("maps/india_admin/IND_adm3.shp"))


EA_points <-SpatialPoints(cbind(EA_join$Long, EA_join$Lat))
taluka_overlay <-over(EA_points, IND_3)
EA_join$Name <- droplevels(taluka_overlay$Name)
EA_join$Taluka <- droplevels(panchayatsOverlay$Taluka)



```




```{r joining by layers}



```


